### ISSUE TITLE
What about subcommands

### ISSUE THREAD

**Issue by crayoned** [cristalhq/acmd#1]
I think it would be nice to have subcommands inside of acmd.Command

**Comment by cristaloleg** [comment]
Good idea, not sure about api for now. Probably `Subcommands []Command` field in each `Command` is a way to solve it, but I don't have real cases, happy to see any examples.

**Comment by crayoned** [comment]
`Subcommands []Command` - looks good. 
Usage: If you have multiple domains in your CLI, each has its own commands. For example, there are many commands in the GO command line interface, run, build, install these are single commands. Also there are commands such as tool, mod, etc., which have their own subcommands.
