### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by GreyXor** [cristalhq/acmd#26]
Hello, how can i execute an specific command (the default one) if no argument is provided

**Comment by cristaloleg** [comment]
Hi, so your case looks like:

```bash
$ ./app
<result of a default command>
```

Right? If so - there is no such feature, you can check `len(os.Args) == 1` before `*Runner.Run()` which means that you don't have params.

```go
type Config struct {
	// DefaultCommand will be run if no params is given. Default is nil which runs help command.
	DefaultCommand *Command
}
```

Can be?

**Comment by GreyXor** [comment]
Thanks for the solution !
and i like the DefaultCommand field :+1:
