### ISSUE TITLE
Support to `<context>:<command>` style

### ISSUE THREAD

**Issue by guiferpa** [cristalhq/acmd#28]
Hey, it's just a suggestion which I can contribute on to create it

Particularly, I like a lot heroku's command style `<context>:<command>` and I looked at that **acmd** doens't has support to put `:` as caracter in a command. What do you think about starting to accept `:` caracter to contemple  this suggestion?

> 🎈  I know that already exists support to put subcommand (congrats for this) but I would like to support `<context>:<command>` as command for example `app:create` or `user:delete`

**Comment by cristaloleg** [comment]
Hi @guiferpa , so tldr you would like to change command name validation to allow `:` ? for me sounds ok, feel free to create a PR 🚀

**Comment by guiferpa** [comment]
@cristaloleg exactly 👍

**Comment by cristaloleg** [comment]
Hm, why closed? 👀

**Comment by guiferpa** [comment]
> Hm, why closed? 👀

my bad, i guessed that the discussion is over then i gonna implement it

**Comment by cristaloleg** [comment]
I have added `.` as an allowed symbol (inspired by https://hexdocs.pm/mix/1.13/Mix.Tasks.Deps.Get.html)
