### ISSUE TITLE
Panic when command list is empty

### ISSUE THREAD

**Issue by sxwebdev** [cristalhq/acmd#61]
Hey, my list of commands is dynamically configured and in some cases it may be empty.
But I still need the version and help command to be executed. At the moment I'm getting the following panic:

```go
panic("acmd: cannot run without commands")
```

Can you fix it?

**Comment by cristaloleg** [comment]
You can add a hidden command. It will not be visible to a user but will prevent such panic.

This should work:
```go
	cmds := []Command{
		{
			Name: "noop",
			ExecFunc: func(ctx context.Context, args []string) error { return nil },
			IsHidden: true,
		},
	}
	r := RunnerOf(cmds, ...
```
